version: '2'
services:
  ssm-mysql:
    image:  'mysql'
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=ssmdb
      - MYSQL_ROOT_PASSWORD=123456
  ssm-web:
    image: 'jetty:9'
    depends_on:
      - ssm-mysql
    links:
      - ssm-mysql
    volumes:
      - ./wars:/var/lib/jetty/webapps
      - ./tools:/tools
    entrypoint: ["/tools/wait-for-it.sh", "ssm-mysql:3306", "-s", "-t", "60", "--", "/docker-entrypoint.sh"]
    ports:
      - "8080:8080"
    environment:
      - ENV_MYSQL_TCP_ADDR=ssm-mysql
      - ENV_MYSQL_TCP_PORT=3306
      - ENV_MYSQL_DATABASE=ssmdb
      - ENV_MYSQL_ACCESS_USERNAME=root
      - ENV_MYSQL_ACCESS_PASSWORD=123456
