export const MUTATION_LOAD_USERS_REQUEST = 'MUTATION_LOAD_USERS_REQUEST';
export const MUTATION_LOAD_USERS_SUCCESS = 'MUTATION_LOAD_USERS_SUCCESS';
export const MUTATION_LOAD_USERS_FAILED = 'MUTATION_LOAD_USERS_FAILED';
export const MUTATION_ADD_USER_FAILED = 'MUTATION_ADD_USER_FAILED';

export const ACTION_LOAD_USERS = 'ACTION_LOAD_USERS';
export const ACTION_ADD_USER = 'ACTION_ADD_USER';
